### ISSUE TITLE
Interested in new commits?

### ISSUE THREAD

**Issue by elliot-nelson** [raphaeleidus/grunt-lazyload#7]
I've been working on a grunt lazy loader that supports loading npm tasks and local modules, with rename support.

Debating whether to release under a new module name, but if you'd be willing to release as a new version of this module I'd make it a PR instead.

**Comment by elliot-nelson** [comment]
Just another ping - @raphaeleidus, curious if you're interested in maintaining this project any more.  My preference would be to update grunt-lazyload to work in more situations, and I'd be willing to put up some PRs, to take over the npm package, or anything in between you feel comfortable with.

**Comment by raphaeleidus** [comment]
Hey, I don't regularly work with grunt any more but super happy to review some PRs and cut a new release
